/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jnitest_myJNI */

#ifndef _Included_com_example_jnitest_myJNI
#define _Included_com_example_jnitest_myJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_jnitest_myJNI
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_jnitest_myJNI_sayHello
  (JNIEnv *, jclass){
  return (*env)->NewStringUTF(env,"JNI hahahahahahahaha");
  };

#ifdef __cplusplus
}
#endif
#endif
